# Generated by Django 3.2.8 on 2021-11-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_administrativeofficer_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('credit', models.IntegerField(default=3)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
